In [1]:
import pandas as pd
import numpy as np

In [4]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movies.merge(credits,on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
movies.shape

(4803, 20)

In [9]:
credits.shape

(4803, 4)

In [10]:
movies=movies.merge(credits,on='title')

In [11]:
movies.shape

(4809, 23)

In [12]:
#genres
#id
#keywords=basically the tags
#title
#overview=if summary of movie is simliar then the movies are similar
#cast
#crew

movies =movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
#missing data
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.dropna(inplace=True)

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
#check for duplicated data
movies.duplicated().sum()

0

In [18]:
#format of genres
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantasy','Scifi']

In [20]:
#data preprocessing
#helping function is convert
 #there is object
    #loop..loop will find dictionary
import ast    
def convert(obj):#here the genre is in string
    L=[]
    for i in ast.literal_eval(obj):#it is one func in ast which converts string into list for looping
        L.append(i['name'])
    return L

In [21]:
movies['genres']=movies['genres'].apply(convert)

In [22]:
movies.head()#genres is sorted

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies['keywords']=movies['keywords'].apply(convert)

In [24]:
movies.head()#keywords is sorted

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
#in cast keep only top 3 actors or dicionary
import ast    
def convert3(obj):#here the genre is in string
    L=[]
    counter=0
    for i in ast.literal_eval(obj):#it is one func in ast which converts string into list for looping
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L 
#if loop for 3 times

In [26]:
movies['cast']=movies['cast'].apply(convert3)

In [27]:
movies.head()#cast is sorted

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
#from crew only extract job=director
import ast    
def fetch_director(obj):#here the genre is in string
    L=[]
    for i in ast.literal_eval(obj):#it is one func in ast which converts string into list for looping
           if i['job']=='Director':
                L.append(i['name'])
                break
    return L

In [29]:
movies['crew']=movies['crew'].apply(fetch_director)

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
#overview is string...convert it to list so that we can concatenate it with others
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [32]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [33]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [35]:
#concatanate the lists and later convert them to string to form a paragrapph
#apply the transformation over the four coloumns to remove the space betwween the two words and make them a single entity
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [36]:
movies.head()# space is remove

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [37]:
#make a new column tags which is concantantiom of four colums
movies['tags']=movies['overview']+movies['genres']+movies['cast']+movies['crew']

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [39]:
#make new dataframe
new_df=movies[['movie_id','title','tags']]

In [40]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [41]:
#convert these list into the strings
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [42]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Admin\AppData\Local\Temp\ipykernel_17104\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [43]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [44]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [45]:
#conert these strings to the lowercase 
new_df['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [46]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\Admin\AppData\Local\Temp\ipykernel_17104\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [47]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [48]:
#text vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [49]:
vectors=cv.fit_transform(new_df['tags']).toarray() #explicitly convert the tags to the numpy array

In [50]:
vectors #each movie is converted to vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
vectors.shape

(4806, 5000)

In [52]:
cv.get_feature_names() # 5000 features

C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970s',
 '1971',
 '1972',
 '1974',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1999',
 '19th',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'accomplished',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adammckay',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'add',
 'addict',
 'addicted',
 'addiction',
 'adds',
 'adjust',
 'adolescent',
 'adopt',
 'adopted',
 'adopts',
 'adorable',
 'adrienbrody',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affections',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'ailing',
 'aim',
 'air',
 'airborne',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'albert',
 'albertbrooks',
 'alcohol',
 'alcoholic',
 'alecbaldwin',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alice',
 'alicebraga',
 'alien',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alter',
 'altering',
 'alternate',
 'alternative',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'amberheard',
 'ambition',
 'ambitious',
 'america',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amusement',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andrew',
 'andrewniccol',
 'andy',
 'andyfickman',
 'andygarcía',
 'andyserkis',
 'andytennant',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymous',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antics',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'arise',
 'aristocrat',
 'armed',
 'armored',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangement',
 'arranges',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'assistant',
 'assume',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'athletes',
 'atlantic',
 'atomegoyan',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attend',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'audreytautou',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'auto',
 'autobiographical',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'banished',
 'bank',
 'banker',
 'bar',
 'barbrastreisand',
 'barely',
 'bargained',
 'barney',
 'baron',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beautiful',
 'beauty',
 'becky',
 'bed',
 'bee',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikers',
 'bilbo',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biographical',
 'biography',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bonniehunt',
 'book',
 'books',
 'boots',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bourne',
 'bout',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breathing',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brewing',
 'brian',
 'briandepalma',
 'brianlevant',
 'brianrobbins',
 'bride',
 'bridge',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutally',
 'bryancranston',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'builds',
 'built',
 'bully',
 'bumbling',
 'bunch',
 'bunny',
 'buried',
 'burned',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cal',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'canine',
 'capable',
 'capital',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'card',
 'care',
 'career',
 'carefree',
 'cares',
 'careymulligan',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherine',
 'catherinedeneuve',
 'catherinehardwicke',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chad',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chazzpalminteri',
 'cheating',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'cindy',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climb',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closed',
 'closer',
 'closing',
 'closure',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'coastal',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehauser',
 'coleridge',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'collapses',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collective',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comfort',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commanding',
 'commit',
 'commitment',
 'commits',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'companions',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'compulsive',
 'computer',
 'conan',
 'concerning',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confidence',
 'confident',
 'conflict',
 'conflicts',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'connect',
 'connected',
 'connecticut',
 'connection',
 'connections',
 'connects',
 'connell',
 'connie',
 'connienielsen',
 'connor',
 'conquer',
 'conrad',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'considers',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'containing',
 'contains',
 'contemporary',
 'contend',
 'contest',
 'continent',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convicts',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corleone',
 'corner',
 'corners',
 'corporate',
 'corporation',
 ...]

In [53]:
#apply stemming
#every word is converted to root word

In [54]:
pip install nltk

^C
Note: you may need to restart the kernel to use updated packages.

In [55]:
import nltk

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.8.1)
Requirement already satisfied: joblib in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: click in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.1.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.5)

In [56]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [57]:
def stem(text):
    y=[]#create a list
    
    for i in text.split(): #string is convertesd to list
        y.append(ps.stem(i))
        
    return " ".join(y)

In [58]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17104\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [59]:
new_df.head() #we hv 4806 vectors with 5000 max used words

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [60]:
#calculate the distance of vector of one movie with the distance of vector of another movie
#recomend the movies that are closer
#gretaer the distance ...similarity is minimum
#will calculate the cosine distance..the angle between the each vector movie

In [61]:
from sklearn.metrics.pairwise import cosine_similarity #silimarity is between 0 and 1 ..if it is 1 then siliarity id high

In [62]:
cosine_similarity(vectors)

array([[1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
        0.        ],
       [0.15389675, 1.        , 0.08830216, ..., 0.03673592, 0.        ,
        0.        ],
       [0.0860663 , 0.08830216, 1.        , ..., 0.03081668, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03673592, 0.03081668, ..., 1.        , 0.07897472,
        0.02746175],
       [0.        , 0.        , 0.        , ..., 0.07897472, 1.        ,
        0.05638839],
       [0.        , 0.        , 0.        , ..., 0.02746175, 0.05638839,
        1.        ]])

In [63]:
similarity = cosine_similarity(vectors)

In [64]:
similarity

array([[1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
        0.        ],
       [0.15389675, 1.        , 0.08830216, ..., 0.03673592, 0.        ,
        0.        ],
       [0.0860663 , 0.08830216, 1.        , ..., 0.03081668, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03673592, 0.03081668, ..., 1.        , 0.07897472,
        0.02746175],
       [0.        , 0.        , 0.        , ..., 0.07897472, 1.        ,
        0.05638839],
       [0.        , 0.        , 0.        , ..., 0.02746175, 0.05638839,
        1.        ]])

In [65]:
similarity[0]

array([1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
       0.        ])

In [66]:
similarity[0].shape # distance of first movie with each movie

(4806,)

In [67]:
list(enumerate(similarity[0])) # it consist of index of movie and similarity with it

[(0, 1.0),
 (1, 0.1538967528127731),
 (2, 0.08606629658238704),
 (3, 0.05923488777590924),
 (4, 0.12048289933537483),
 (5, 0.15339299776947407),
 (6, 0.035355339059327376),
 (7, 0.22056438662814232),
 (8, 0.08944271909999159),
 (9, 0.11180339887498947),
 (10, 0.1632993161855452),
 (11, 0.11338934190276817),
 (12, 0.16269784336399212),
 (13, 0.07071067811865475),
 (14, 0.17213259316477408),
 (15, 0.07669649888473704),
 (16, 0.1224744871391589),
 (17, 0.13801311186847084),
 (18, 0.06030226891555272),
 (19, 0.11028219331407116),
 (20, 0.07961173386514128),
 (21, 0.08451542547285165),
 (22, 0.10846522890932808),
 (23, 0.15),
 (24, 0.08606629658238704),
 (25, 0.02795084971874737),
 (26, 0.18257418583505539),
 (27, 0.16137430609197573),
 (28, 0.1732050807568877),
 (29, 0.09784921095801634),
 (30, 0.11028219331407116),
 (31, 0.21693045781865616),
 (32, 0.0659380473395787),
 (33, 0.158113883008419),
 (34, 0.0),
 (35, 0.17928429140015906),
 (36, 0.1976423537605237),
 (37, 0.08770580193070293),
 (38, 0.08588975014708022),
 (39, 0.12909944487358055),
 (40, 0.08451542547285165),
 (41, 0.10476454436543672),
 (42, 0.0),
 (43, 0.15339299776947407),
 (44, 0.06741998624632421),
 (45, 0.12524485821702988),
 (46, 0.18257418583505539),
 (47, 0.15655607277128736),
 (48, 0.06030226891555272),
 (49, 0.0),
 (50, 0.12456821978060995),
 (51, 0.09045340337332908),
 (52, 0.12909944487358055),
 (53, 0.0778498944161523),
 (54, 0.06201736729460423),
 (55, 0.08660254037844385),
 (56, 0.158113883008419),
 (57, 0.0),
 (58, 0.06388765649999399),
 (59, 0.08451542547285164),
 (60, 0.0),
 (61, 0.2051956704170308),
 (62, 0.12909944487358058),
 (63, 0.0778498944161523),
 (64, 0.05590169943749474),
 (65, 0.03296902366978935),
 (66, 0.03627381250550058),
 (67, 0.12048289933537483),
 (68, 0.2051956704170308),
 (69, 0.04969039949999532),
 (70, 0.11180339887498947),
 (71, 0.10882143751650175),
 (72, 0.18650096164806276),
 (73, 0.07071067811865475),
 (74, 0.1556997888323046),
 (75, 0.09128709291752769),
 (76, 0.12048289933537483),
 (77, 0.0),
 (78, 0.09325048082403138),
 (79, 0.11338934190276817),
 (80, 0.05163977794943222),
 (81, 0.08075728530872482),
 (82, 0.09534625892455922),
 (83, 0.19364916731037088),
 (84, 0.1535737792084878),
 (85, 0.07319250547113998),
 (86, 0.0778498944161523),
 (87, 0.1315587028960544),
 (88, 0.1025978352085154),
 (89, 0.04170288281141495),
 (90, 0.09534625892455922),
 (91, 0.16609095970747992),
 (92, 0.07905694150420947),
 (93, 0.07453559924999298),
 (94, 0.21693045781865616),
 (95, 0.09534625892455922),
 (96, 0.12909944487358055),
 (97, 0.10741723110591492),
 (98, 0.16269784336399212),
 (99, 0.039528470752104736),
 (100, 0.05423261445466404),
 (101, 0.1315587028960544),
 (102, 0.12060453783110545),
 (103, 0.10476454436543672),
 (104, 0.09759000729485331),
 (105, 0.11547005383792514),
 (106, 0.07352146220938077),
 (107, 0.1318760946791574),
 (108, 0.11338934190276817),
 (109, 0.12909944487358058),
 (110, 0.0),
 (111, 0.12909944487358055),
 (112, 0.08944271909999159),
 (113, 0.07905694150420947),
 (114, 0.0778498944161523),
 (115, 0.08606629658238704),
 (116, 0.08304547985373996),
 (117, 0.10540925533894599),
 (118, 0.02862991671569341),
 (119, 0.042257712736425826),
 (120, 0.0),
 (121, 0.12456821978060995),
 (122, 0.158113883008419),
 (123, 0.13987572123604708),
 (124, 0.06900655593423542),
 (125, 0.06674912392349772),
 (126, 0.11858541225631421),
 (127, 0.16770509831248423),
 (128, 0.0),
 (129, 0.10350983390135313),
 (130, 0.044721359549995794),
 (131, 0.14704292441876154),
 (132, 0.07254762501100116),
 (133, 0.049999999999999996),
 (134, 0.16770509831248423),
 (135, 0.0),
 (136, 0.03726779962499649),
 (137, 0.023186944788008413),
 (138, 0.14638501094227996),
 (139, 0.15339299776947407),
 (140, 0.06984302957695782),
 (141, 0.06454972243679029),
 (142, 0.09325048082403138),
 (143, 0.09784921095801634),
 (144, 0.1025978352085154),
 (145, 0.03261640365267211),
 (146, 0.0),
 (147, 0.0816496580927726),
 (148, 0.1538967528127731),
 (149, 0.17677669529663687),
 (150, 0.18257418583505539),
 (151, 0.26967994498529685),
 (152, 0.09999999999999999),
 (153, 0.09128709291752768),
 (154, 0.04767312946227961),
 (155, 0.0),
 (156, 0.03892494720807615),
 (157, 0.10540925533894599),
 (158, 0.14907119849998596),
 (159, 0.11180339887498948),
 (160, 0.08519427513705971),
 (161, 0.07453559924999298),
 (162, 0.049999999999999996),
 (163, 0.07905694150420947),
 (164, 0.11858541225631421),
 (165, 0.1025978352085154),
 (166, 0.14638501094227996),
 (167, 0.08944271909999159),
 (168, 0.15118578920369088),
 (169, 0.10882143751650175),
 (170, 0.10476454436543672),
 (171, 0.039528470752104736),
 (172, 0.11952286093343936),
 (173, 0.0),
 (174, 0.17541160386140586),
 (175, 0.08032193289024989),
 (176, 0.05773502691896257),
 (177, 0.0),
 (178, 0.03779644730092272),
 (179, 0.05423261445466404),
 (180, 0.03726779962499649),
 (181, 0.0408248290463863),
 (182, 0.11858541225631421),
 (183, 0.09682458365518543),
 (184, 0.11028219331407116),
 (185, 0.08451542547285165),
 (186, 0.06454972243679029),
 (187, 0.15339299776947407),
 (188, 0.035355339059327376),
 (189, 0.05976143046671968),
 (190, 0.06030226891555272),
 (191, 0.0816496580927726),
 (192, 0.0),
 (193, 0.08808303292720551),
 (194, 0.0),
 (195, 0.08944271909999159),
 (196, 0.09999999999999999),
 (197, 0.06984302957695782),
 (198, 0.09128709291752769),
 (199, 0.20080483222562473),
 (200, 0.1414213562373095),
 (201, 0.0),
 (202, 0.052704627669472995),
 (203, 0.1315587028960544),
 (204, 0.04016096644512494),
 (205, 0.10540925533894599),
 (206, 0.16137430609197573),
 (207, 0.13693063937629155),
 (208, 0.20225995873897262),
 (209, 0.052704627669472995),
 (210, 0.0778498944161523),
 (211, 0.03892494720807615),
 (212, 0.11677484162422844),
 (213, 0.11180339887498947),
 (214, 0.03779644730092272),
 (215, 0.12048289933537483),
 (216, 0.11180339887498948),
 (217, 0.06388765649999399),
 (218, 0.05976143046671968),
 (219, 0.09128709291752769),
 (220, 0.08944271909999159),
 (221, 0.03726779962499649),
 (222, 0.09045340337332908),
 (223, 0.07559289460184544),
 (224, 0.061429511683395124),
 (225, 0.0778498944161523),
 (226, 0.0),
 (227, 0.09534625892455922),
 (228, 0.1414213562373095),
 (229, 0.07851358838853205),
 (230, 0.11952286093343936),
 (231, 0.0),
 (232, 0.19518001458970663),
 (233, 0.158113883008419),
 (234, 0.10741723110591492),
 (235, 0.08770580193070293),
 (236, 0.09534625892455922),
 (237, 0.09759000729485331),
 (238, 0.12171612389003691),
 (239, 0.061429511683395124),
 (240, 0.08606629658238704),
 (241, 0.1224744871391589),
 (242, 0.13693063937629155),
 (243, 0.11677484162422844),
 (244, 0.049999999999999996),
 (245, 0.09999999999999999),
 (246, 0.03450327796711771),
 (247, 0.0),
 (248, 0.07071067811865475),
 (249, 0.11547005383792514),
 (250, 0.0),
 (251, 0.0),
 (252, 0.035355339059327376),
 (253, 0.06030226891555272),
 (254, 0.08304547985373996),
 (255, 0.0),
 (256, 0.13483997249264842),
 (257, 0.08606629658238704),
 (258, 0.03131121455425747),
 (259, 0.1025978352085154),
 (260, 0.1538967528127731),
 (261, 0.045643546458763846),
 (262, 0.11858541225631421),
 (263, 0.15),
 (264, 0.0),
 (265, 0.045643546458763846),
 (266, 0.09999999999999999),
 (267, 0.10846522890932808),
 (268, 0.042257712736425826),
 (269, 0.0),
 (270, 0.1267731382092775),
 (271, 0.11858541225631421),
 (272, 0.0),
 (273, 0.03834824944236852),
 (274, 0.046373889576016826),
 (275, 0.15),
 (276, 0.1025978352085154),
 (277, 0.09682458365518543),
 (278, 0.11504474832710555),
 (279, 0.11180339887498947),
 (280, 0.0),
 (281, 0.07559289460184544),
 (282, 0.08770580193070293),
 (283, 0.0),
 (284, 0.0),
 (285, 0.031008683647302113),
 (286, 0.03627381250550058),
 (287, 0.0),
 (288, 0.0),
 (289, 0.07161148740394328),
 (290, 0.09534625892455922),
 (291, 0.08451542547285165),
 (292, 0.1538967528127731),
 (293, 0.04767312946227961),
 (294, 0.08304547985373996),
 (295, 0.042257712736425826),
 (296, 0.06900655593423542),
 (297, 0.03726779962499649),
 (298, 0.0),
 (299, 0.06388765649999399),
 (300, 0.1267731382092775),
 (301, 0.09128709291752768),
 (302, 0.08451542547285165),
 (303, 0.04152273992686998),
 (304, 0.04850712500726659),
 (305, 0.11180339887498947),
 (306, 0.08770580193070293),
 (307, 0.09376144618769908),
 (308, 0.05423261445466404),
 (309, 0.09999999999999999),
 (310, 0.05547001962252292),
 (311, 0.16064386578049977),
 (312, 0.14509525002200233),
 (313, 0.05590169943749474),
 (314, 0.0),
 (315, 0.1267731382092775),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09999999999999999),
 (320, 0.04767312946227961),
 (321, 0.0),
 (322, 0.2051956704170308),
 (323, 0.0),
 (324, 0.03726779962499649),
 (325, 0.09128709291752769),
 (326, 0.04303314829119352),
 (327, 0.045643546458763846),
 (328, 0.0),
 (329, 0.13693063937629155),
 (330, 0.16269784336399212),
 (331, 0.06819943394704735),
 (332, 0.1267731382092775),
 (333, 0.04879500364742666),
 (334, 0.11504474832710555),
 (335, 0.08606629658238704),
 (336, 0.1025978352085154),
 (337, 0.03580574370197164),
 (338, 0.0),
 (339, 0.09128709291752769),
 (340, 0.0816496580927726),
 (341, 0.09128709291752769),
 (342, 0.10927167294163061),
 (343, 0.032274861218395144),
 (344, 0.042257712736425826),
 (345, 0.03162277660168379),
 (346, 0.0),
 (347, 0.0),
 (348, 0.04767312946227961),
 (349, 0.1341640786499874),
 (350, 0.07352146220938077),
 (351, 0.0),
 (352, 0.045643546458763846),
 (353, 0.033709993123162106),
 (354, 0.0),
 (355, 0.06324555320336758),
 (356, 0.09534625892455922),
 (357, 0.0),
 (358, 0.09759000729485331),
 (359, 0.04767312946227961),
 (360, 0.0),
 (361, 0.04303314829119352),
 (362, 0.09128709291752769),
 (363, 0.06741998624632421),
 (364, 0.036760731104690386),
 (365, 0.08304547985373996),
 (366, 0.08032193289024989),
 (367, 0.0),
 (368, 0.09534625892455922),
 (369, 0.1267731382092775),
 (370, 0.09128709291752769),
 (371, 0.10476454436543672),
 (372, 0.07905694150420947),
 (373, 0.11547005383792514),
 (374, 0.06324555320336758),
 (375, 0.030714755841697562),
 (376, 0.07352146220938077),
 (377, 0.0),
 (378, 0.0),
 (379, 0.07191949522280762),
 (380, 0.0),
 (381, 0.12403473458920845),
 (382, 0.0),
 (383, 0.08032193289024989),
 (384, 0.045643546458763846),
 (385, 0.0),
 (386, 0.03779644730092272),
 (387, 0.04303314829119352),
 (388, 0.0),
 (389, 0.09128709291752769),
 (390, 0.044721359549995794),
 (391, 0.02988071523335984),
 (392, 0.043852900965351466),
 (393, 0.0),
 (394, 0.039528470752104736),
 (395, 0.0),
 (396, 0.04016096644512494),
 (397, 0.0),
 (398, 0.0),
 (399, 0.039528470752104736),
 (400, 0.15),
 (401, 0.0),
 (402, 0.07905694150420947),
 (403, 0.15971914124998499),
 (404, 0.049999999999999996),
 (405, 0.04662524041201569),
 (406, 0.03162277660168379),
 (407, 0.031008683647302113),
 (408, 0.05423261445466404),
 (409, 0.0),
 (410, 0.10606601717798213),
 (411, 0.0778498944161523),
 (412, 0.13483997249264842),
 (413, 0.11504474832710555),
 (414, 0.04152273992686998),
 (415, 0.05872202195147034),
 (416, 0.045643546458763846),
 (417, 0.052704627669472995),
 (418, 0.0),
 (419, 0.10606601717798213),
 (420, 0.1813690625275029),
 (421, 0.0),
 (422, 0.12909944487358058),
 (423, 0.04016096644512494),
 (424, 0.06324555320336758),
 (425, 0.0816496580927726),
 (426, 0.08451542547285164),
 (427, 0.0408248290463863),
 (428, 0.05773502691896257),
 (429, 0.0),
 (430, 0.04152273992686998),
 (431, 0.04662524041201569),
 (432, 0.07559289460184544),
 (433, 0.04879500364742666),
 (434, 0.0),
 (435, 0.05423261445466404),
 (436, 0.0),
 (437, 0.042257712736425826),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.04662524041201569),
 (442, 0.07905694150420947),
 (443, 0.039528470752104736),
 (444, 0.0),
 (445, 0.0),
 (446, 0.043852900965351466),
 (447, 0.035355339059327376),
 (448, 0.0),
 (449, 0.09534625892455922),
 (450, 0.03726779962499649),
 (451, 0.039528470752104736),
 (452, 0.04879500364742666),
 (453, 0.04016096644512494),
 (454, 0.08304547985373996),
 (455, 0.052704627669472995),
 (456, 0.06741998624632421),
 (457, 0.07352146220938077),
 (458, 0.032274861218395144),
 (459, 0.05590169943749474),
 (460, 0.0),
 (461, 0.14301938838683884),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.19999999999999998),
 (467, 0.12524485821702988),
 (468, 0.045643546458763846),
 (469, 0.06523280730534423),
 (470, 0.03834824944236852),
 (471, 0.07559289460184544),
 (472, 0.11504474832710555),
 (473, 0.11504474832710555),
 (474, 0.0),
 (475, 0.10350983390135313),
 (476, 0.09999999999999999),
 (477, 0.0),
 (478, 0.06666666666666667),
 (479, 0.026919095102908273),
 (480, 0.07559289460184544),
 (481, 0.0),
 (482, 0.0),
 (483, 0.19518001458970663),
 (484, 0.049999999999999996),
 (485, 0.08451542547285165),
 (486, 0.08195375470622296),
 (487, 0.16770509831248423),
 (488, 0.0790569415042095),
 (489, 0.0),
 (490, 0.1732050807568877),
 (491, 0.06900655593423542),
 (492, 0.04152273992686998),
 (493, 0.0),
 (494, 0.0),
 (495, 0.22360679774997896),
 (496, 0.0),
 (497, 0.0),
 (498, 0.1025978352085154),
 (499, 0.0),
 (500, 0.0408248290463863),
 (501, 0.07254762501100116),
 (502, 0.07254762501100116),
 (503, 0.08451542547285165),
 (504, 0.0),
 (505, 0.16269784336399212),
 (506, 0.0),
 (507, 0.17677669529663687),
 (508, 0.16064386578049977),
 (509, 0.036760731104690386),
 (510, 0.08770580193070293),
 (511, 0.14638501094227996),
 (512, 0.043852900965351466),
 (513, 0.11858541225631421),
 (514, 0.039528470752104736),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.07352146220938077),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.07071067811865475),
 (524, 0.0),
 (525, 0.0408248290463863),
 (526, 0.0),
 (527, 0.0),
 (528, 0.039528470752104736),
 (529, 0.16854996561581054),
 (530, 0.04767312946227961),
 (531, 0.06984302957695782),
 (532, 0.0),
 (533, 0.05423261445466404),
 (534, 0.05773502691896257),
 (535, 0.11028219331407116),
 (536, 0.0),
 (537, 0.10846522890932808),
 (538, 0.0),
 (539, 0.18650096164806276),
 (540, 0.07669649888473704),
 (541, 0.06085806194501846),
 (542, 0.05725983343138682),
 (543, 0.10350983390135313),
 (544, 0.09128709291752769),
 (545, 0.0408248290463863),
 (546, 0.052704627669472995),
 (547, 0.11180339887498948),
 (548, 0.0),
 (549, 0.07352146220938077),
 (550, 0.0),
 (551, 0.035355339059327376),
 (552, 0.0),
 (553, 0.05423261445466404),
 (554, 0.0),
 (555, 0.024253562503633294),
 (556, 0.04152273992686998),
 (557, 0.07559289460184544),
 (558, 0.0),
 (559, 0.0),
 (560, 0.03162277660168379),
 (561, 0.05976143046671968),
 (562, 0.0),
 (563, 0.036760731104690386),
 (564, 0.05590169943749474),
 (565, 0.06201736729460423),
 (566, 0.035355339059327376),
 (567, 0.0),
 (568, 0.18257418583505539),
 (569, 0.035355339059327376),
 (570, 0.12403473458920845),
 (571, 0.03333333333333333),
 (572, 0.09302605094190634),
 (573, 0.03580574370197164),
 (574, 0.03261640365267211),
 (575, 0.03834824944236852),
 (576, 0.04152273992686998),
 (577, 0.13987572123604708),
 (578, 0.03261640365267211),
 (579, 0.05590169943749474),
 (580, 0.034099716973523674),
 (581, 0.18257418583505539),
 (582, 0.1267731382092775),
 (583, 0.07905694150420947),
 (584, 0.07905694150420947),
 (585, 0.0),
 (586, 0.06085806194501846),
 (587, 0.1556997888323046),
 (588, 0.036760731104690386),
 (589, 0.07453559924999298),
 (590, 0.04767312946227961),
 (591, 0.0816496580927726),
 (592, 0.03779644730092272),
 (593, 0.0),
 (594, 0.10846522890932808),
 (595, 0.10350983390135313),
 (596, 0.13333333333333333),
 (597, 0.09128709291752769),
 (598, 0.0),
 (599, 0.02439750182371333),
 (600, 0.06454972243679029),
 (601, 0.05096471914376255),
 (602, 0.06984302957695782),
 (603, 0.0816496580927726),
 (604, 0.09999999999999999),
 (605, 0.0),
 (606, 0.0),
 (607, 0.09128709291752768),
 (608, 0.0),
 (609, 0.03779644730092272),
 (610, 0.08195375470622296),
 (611, 0.03580574370197164),
 (612, 0.07071067811865475),
 (613, 0.0512989176042577),
 (614, 0.0512989176042577),
 (615, 0.04879500364742666),
 (616, 0.0),
 (617, 0.09759000729485331),
 (618, 0.15118578920369088),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0512989176042577),
 (622, 0.03042903097250923),
 (623, 0.0),
 (624, 0.11952286093343936),
 (625, 0.0),
 (626, 0.1025978352085154),
 (627, 0.16770509831248423),
 (628, 0.0),
 (629, 0.03450327796711771),
 (630, 0.0),
 (631, 0.04016096644512494),
 (632, 0.07453559924999298),
 (633, 0.03261640365267211),
 (634, 0.14301938838683884),
 (635, 0.04016096644512494),
 (636, 0.043852900965351466),
 (637, 0.04662524041201569),
 (638, 0.0),
 (639, 0.0),
 (640, 0.07669649888473704),
 (641, 0.0),
 (642, 0.0),
 (643, 0.07559289460184544),
 (644, 0.08944271909999159),
 (645, 0.08304547985373996),
 (646, 0.0816496580927726),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.05976143046671968),
 (654, 0.13968605915391563),
 (655, 0.03627381250550058),
 (656, 0.0),
 (657, 0.05423261445466404),
 (658, 0.0778498944161523),
 (659, 0.04016096644512494),
 (660, 0.09759000729485331),
 (661, 0.09302605094190634),
 (662, 0.0),
 (663, 0.0),
 (664, 0.08606629658238704),
 (665, 0.07161148740394328),
 (666, 0.0),
 (667, 0.0),
 (668, 0.09759000729485331),
 (669, 0.0),
 (670, 0.0),
 (671, 0.03892494720807615),
 (672, 0.09999999999999999),
 (673, 0.03726779962499649),
 (674, 0.0659380473395787),
 (675, 0.07559289460184544),
 (676, 0.04662524041201569),
 (677, 0.05423261445466404),
 (678, 0.0816496580927726),
 (679, 0.0),
 (680, 0.03726779962499649),
 (681, 0.0),
 (682, 0.0),
 (683, 0.07352146220938077),
 (684, 0.0),
 (685, 0.05423261445466404),
 (686, 0.0),
 (687, 0.08304547985373996),
 (688, 0.0),
 (689, 0.0),
 (690, 0.04152273992686998),
 (691, 0.12909944487358058),
 (692, 0.0408248290463863),
 (693, 0.0),
 (694, 0.03627381250550058),
 (695, 0.11180339887498948),
 (696, 0.0),
 (697, 0.0),
 (698, 0.033709993123162106),
 (699, 0.0),
 (700, 0.049999999999999996),
 (701, 0.0),
 (702, 0.042257712736425826),
 (703, 0.0),
 (704, 0.043852900965351466),
 (705, 0.0),
 (706, 0.03779644730092272),
 (707, 0.0),
 (708, 0.043852900965351466),
 (709, 0.0),
 (710, 0.030714755841697562),
 (711, 0.09325048082403138),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.15),
 (716, 0.045643546458763846),
 (717, 0.0),
 (718, 0.06523280730534423),
 (719, 0.0),
 (720, 0.043852900965351466),
 (721, 0.04767312946227961),
 (722, 0.0),
 (723, 0.03580574370197164),
 (724, 0.04152273992686998),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0512989176042577),
 (728, 0.11338934190276817),
 (729, 0.0),
 (730, 0.023063280200722125),
 (731, 0.08032193289024989),
 (732, 0.10741723110591492),
 (733, 0.0),
 (734, 0.07254762501100116),
 (735, 0.06984302957695782),
 (736, 0.0512989176042577),
 (737, 0.049999999999999996),
 (738, 0.0),
 (739, 0.05423261445466404),
 (740, 0.11338934190276817),
 (741, 0.08304547985373996),
 (742, 0.049999999999999996),
 (743, 0.03726779962499649),
 (744, 0.10540925533894599),
 (745, 0.08606629658238704),
 (746, 0.11858541225631421),
 (747, 0.031008683647302113),
 (748, 0.05590169943749474),
 (749, 0.0),
 (750, 0.0408248290463863),
 (751, 0.0),
 (752, 0.03834824944236852),
 (753, 0.04303314829119352),
 (754, 0.08770580193070293),
 (755, 0.09302605094190634),
 (756, 0.0),
 (757, 0.0),
 (758, 0.03580574370197164),
 (759, 0.0),
 (760, 0.0),
 (761, 0.04303314829119352),
 (762, 0.05590169943749474),
 (763, 0.0),
 (764, 0.042257712736425826),
 (765, 0.0),
 (766, 0.0),
 (767, 0.07559289460184544),
 (768, 0.09784921095801634),
 (769, 0.04662524041201569),
 (770, 0.03892494720807615),
 (771, 0.0),
 (772, 0.0),
 (773, 0.09999999999999999),
 (774, 0.06741998624632421),
 (775, 0.0816496580927726),
 (776, 0.05976143046671968),
 (777, 0.09682458365518543),
 (778, 0.09128709291752769),
 (779, 0.0),
 (780, 0.0),
 (781, 0.10846522890932808),
 (782, 0.10476454436543672),
 (783, 0.0512989176042577),
 (784, 0.13987572123604708),
 (785, 0.05345224838248488),
 (786, 0.11677484162422844),
 (787, 0.08032193289024989),
 (788, 0.07669649888473704),
 (789, 0.0),
 (790, 0.06666666666666667),
 (791, 0.049999999999999996),
 (792, 0.042257712736425826),
 (793, 0.039528470752104736),
 (794, 0.1538967528127731),
 (795, 0.0),

In [68]:
#apply sorting
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]# dont sort according to index...sort on the basis of second value

[(151, 0.26967994498529685),
 (4405, 0.25819888974716115),
 (942, 0.24913643956121986),
 (1444, 0.2480694691784169),
 (1194, 0.2439750182371333)]

In [69]:
#cretae a function recommend ...which in return will give five best movies 
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]#find the index of movie
    distances=similarity[movie_index]#find the similarity
    #sort in the descending order
    #but indexing is lost in sort thats why enmumerate function is used
    movies_list= sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    return

In [70]:
recommend('Batman Begins')

Amidst the Devil's Wings
The Dark Knight Rises
The Dark Knight
Batman
Dead Man Down

In [71]:
#by index fetch the movie name 
new_df.iloc[2999]

movie_id                                                 9355
title                              Mad Max Beyond Thunderdome
tags        mad max becom a pawn in a decad oasi of a tech...
Name: 3000, dtype: object

In [72]:
import pickle

In [74]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [75]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)